apiVersion: v1
kind: Pod
metadata:
  name: yoda-pod
  labels:
    app: yoda
spec:
  containers:
    - name: nginx
      image: bitnami/nginx
      ports:
        - containerPort: 8080
      livenessProbe:
        tcpSocket:
          port: 8080
      readinessProbe:
        tcpSocket:
          port: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: yoda-service
  labels:
    app: yoda
spec:
  ports:
    - port: 80
      name: http
      targetPort: 8080
  selector:
    app: yoda
